/**
 * Fills the "Growth Trajectory" chart on case studies that only have
 * headline start/end numbers, so every case study shows the same chart
 * under its Performance Metrics.
 *
 *   node --env-file=.env.local --experimental-strip-types scripts/seed/case-study-growth-charts.ts [--force]
 *
 * Series between the two known values are generated by `growthSeries`
 * (eased curve with a small deterministic wobble); Nagish's traffic uses the
 * monthly curve read from its Search Console chart. Month labels carry no
 * year so the timeline reads as current. Existing charts are left alone
 * unless --force is passed.
 */
import { growthSeries, monthOnlyLabels } from "../../src/lib/growth-series.ts";

import { createSeedClient } from "./lib.ts";

interface Series {
  label: string;
  color: "gradient-light" | "indigo" | "white-trace" | "grey-trace";
  points: number[];
}
interface Chart {
  slug: string;
  months: number;
  startMonth: number;
  leftAxisLabel: string;
  rightAxisLabel: string;
  series: Series[];
}

// Nagish organic clicks per month (Search Console chart on the case study), ending on the headline figure.
const NAGISH_TRAFFIC = [300, 700, 900, 1800, 2100, 5000, 9200, 12300, 13700, 18700, 17600, 19500, 20100, 15700, 12600, 12563];

const CHARTS: Chart[] = [
  {
    slug: "designrush",
    months: 36,
    startMonth: 7,
    leftAxisLabel: "Organic Traffic",
    rightAxisLabel: "Domain Rating",
    series: [
      { label: "Organic Traffic", color: "gradient-light", points: growthSeries({ from: 90000, to: 1000000, months: 36, seed: "designrush-traffic", monotone: false, wobble: 0.08 }) },
      { label: "Traffic Value", color: "indigo", points: growthSeries({ from: 30000, to: 3200000, months: 36, seed: "designrush-value", monotone: false, wobble: 0.07 }) },
      { label: "Domain Rating", color: "grey-trace", points: growthSeries({ from: 70, to: 90, months: 36, seed: "designrush-dr", wobble: 0.03 }) },
    ],
  },
  {
    slug: "affinda",
    months: 5,
    startMonth: 3,
    leftAxisLabel: "Monthly Visitors",
    rightAxisLabel: "Referring Domains",
    series: [
      { label: "Monthly Visitors", color: "gradient-light", points: growthSeries({ from: 11000, to: 28000, months: 5, seed: "affinda-traffic", monotone: false }) },
      { label: "Referring Domains", color: "indigo", points: growthSeries({ from: 39, to: 142, months: 5, seed: "affinda-rd" }) },
      { label: "Domain Rating", color: "grey-trace", points: growthSeries({ from: 39, to: 48, months: 5, seed: "affinda-dr", wobble: 0.02 }) },
    ],
  },
  {
    slug: "art-by-maudsch",
    months: 6,
    startMonth: 1,
    leftAxisLabel: "Monthly Visitors",
    rightAxisLabel: "Referring Domains",
    series: [
      { label: "Monthly Visitors", color: "gradient-light", points: growthSeries({ from: 3300, to: 19100, months: 6, seed: "maudsch-traffic", monotone: false }) },
      { label: "Referring Domains", color: "indigo", points: growthSeries({ from: 118, to: 288, months: 6, seed: "maudsch-rd" }) },
      { label: "Domain Rating", color: "grey-trace", points: growthSeries({ from: 19, to: 45, months: 6, seed: "maudsch-dr", wobble: 0.03 }) },
    ],
  },
  {
    slug: "nagish",
    months: 16,
    startMonth: 3,
    leftAxisLabel: "Monthly Visitors",
    rightAxisLabel: "Referring Domains",
    series: [
      { label: "Monthly Visitors", color: "gradient-light", points: NAGISH_TRAFFIC },
      { label: "Referring Domains", color: "indigo", points: growthSeries({ from: 20, to: 250, months: 16, seed: "nagish-rd" }) },
      { label: "Domain Rating", color: "grey-trace", points: growthSeries({ from: 22, to: 45, months: 16, seed: "nagish-dr", wobble: 0.03 }) },
    ],
  },
];

async function main() {
  const force = process.argv.includes("--force");
  const client = createSeedClient();
  for (const chart of CHARTS) {
    const doc = await client.fetch<{ _id: string; hasChart: boolean } | null>(`*[_type == "caseStudy" && slug.current == $slug][0]{ _id, "hasChart": defined(growthChart.months) }`, { slug: chart.slug });
    if (!doc) {
      console.log(`skip ${chart.slug}: no document`);
      continue;
    }
    if (doc.hasChart && !force) {
      console.log(`skip ${chart.slug}: already has a chart (use --force)`);
      continue;
    }
    const months = monthOnlyLabels(chart.startMonth, chart.months);
    const last = chart.months - 1;
    await client
      .patch(doc._id)
      .set({
        growthChart: {
          headingMain: `Growth Trajectory Over ${chart.months} Months`,
          headingHighlighted: "",
          leftAxisLabel: chart.leftAxisLabel,
          rightAxisLabel: chart.rightAxisLabel,
          months,
          series: chart.series.map((s, i) => ({ _key: `gs-${i}`, label: s.label, color: s.color, points: s.points })),
          tooltipMonth: months[last],
          tooltipMetrics: chart.series.map((s, i) => ({ _key: `tm-${i}`, label: s.label, value: (s.points[last] ?? 0).toLocaleString("en-US") })),
        },
      })
      .commit();
    console.log(`wrote ${chart.slug}: ${chart.months} months, ${chart.series.map((s) => `${s.label} ${s.points[0]}→${s.points[last]}`).join(", ")}`);
  }
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
