import { SITE_INDEXING_ENABLED } from "@/lib/indexing";
import { SITE_URL } from "@/lib/site";

/**
 * robots.txt as a route handler rather than Next's metadata helper, because
 * the helper cannot emit comment lines and the file carries the Heroic
 * Rankings shield (same as the live site). Rules are unchanged: everything is
 * disallowed until NEXT_PUBLIC_SITE_INDEXING=true (see src/lib/indexing.ts).
 */
export const dynamic = "force-static";

const SHIELD = String.raw`
#                                      .........    
#                                      .........    
#                                      .........    
#                      ........        .........    
#                     ..........       .........    
#                     ..........       .........    
#                     ..........       .........    
#     .........       ..........       .........    
#     .........       ..........       .........    
#     .........       ..........       .........    
#     .........       ..........       .........    
#     .........        ........        .........    
#     .........                        .........    
#      ........                        ........     
#        ......       ..........       ......       
#          ....       ..........       ....         
#            ..       ..........       ..           
#                     ..........                    
#                     ..........                    
#                     ..........                    
#                      ........                     
#                        ....                       
`;

export function buildRobotsTxt(indexingEnabled = SITE_INDEXING_ENABLED): string {
  const rules = indexingEnabled
    ? ["User-agent: *", "Allow: /", "Disallow: /api/", "Disallow: /studio/", "Disallow: /navbar-preview/"]
    : ["User-agent: *", "Disallow: /"];
  return `${rules.join("\n")}\n\nSitemap: ${SITE_URL}/sitemap.xml\n${SHIELD}`;
}

export function GET() {
  return new Response(buildRobotsTxt(), {
    headers: { "Content-Type": "text/plain; charset=utf-8", "Cache-Control": "public, max-age=3600" },
  });
}
